/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 2026 KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "gerber_to_svg.h"
#include "gerber_file_image.h"
#include "gerber_render.h"

#include <base_units.h>
#include <jobs/job_gerber_export_svg.h>
#include <macros.h>
#include <page_info.h>
#include <plotters/plotters_pslike.h>
#include <string_utils.h>

#include <fmt/format.h>
#include <wx/filename.h>


namespace
{

wxString svgXmlEsc( const wxString& aStr )
{
    wxString escaped;

    escaped.reserve( aStr.length() );

    for( wxString::const_iterator it = aStr.begin(); it != aStr.end(); ++it )
    {
        const wxChar c = *it;

        switch( c )
        {
        case wxS( '<' ):  escaped.append( wxS( "&lt;" ) );  break;
        case wxS( '>' ):  escaped.append( wxS( "&gt;" ) );  break;
        case wxS( '&' ):  escaped.append( wxS( "&amp;" ) ); break;
        case wxS( '\r' ): escaped.append( wxS( "&#xD;" ) ); break;
        default:          escaped.append( c );               break;
        }
    }

    return escaped;
}


class GERBER_SVG_PLOTTER : public SVG_PLOTTER
{
public:
    void SetExactPageSizeMm( double aWidthMm, double aHeightMm )
    {
        m_exactWidthMm = aWidthMm;
        m_exactHeightMm = aHeightMm;
    }

    bool StartPlot( const wxString& aPageNumber ) override
    {
        wxASSERT( m_outputFile );

        std::string header = "<?xml version=\"1.0\" standalone=\"no\"?>\n"
                " <!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \n"
                " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"> \n"
                "<svg\n"
                "  xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
                "  xmlns=\"http://www.w3.org/2000/svg\"\n"
                "  xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n"
                "  xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
                "  version=\"1.1\"\n";

        fmt::print( m_outputFile, "{}", header );
        fmt::print( m_outputFile,
                    "  width=\"{:.{}f}mm\" height=\"{:.{}f}mm\" "
                    "viewBox=\"0.0000 0.0000 {:.{}f} {:.{}f}\">\n",
                    m_exactWidthMm, m_precision,
                    m_exactHeightMm, m_precision,
                    m_exactWidthMm, m_precision,
                    m_exactHeightMm, m_precision );

        wxString date = GetISO8601CurrentDateTime();

        fmt::print( m_outputFile, "<title>SVG Image created as {} date {} </title>\n",
                    TO_UTF8( svgXmlEsc( wxFileName( m_filename ).GetFullName() ) ),
                    TO_UTF8( date ) );
        fmt::print( m_outputFile, "  <desc>Image generated by {} </desc>\n",
                    TO_UTF8( svgXmlEsc( m_creator ) ) );
        fmt::print( m_outputFile,
                    "<g style=\"fill:#{:06X}; fill-opacity:{:.{}f};stroke:#{:06X}; stroke-opacity:1.0000;\n",
                    m_brush_rgb_color,
                    m_brush_alpha,
                    m_precision,
                    m_pen_rgb_color );
        fmt::print( m_outputFile, "stroke-linecap:round; stroke-linejoin:round;\"\n" );
        fmt::print( m_outputFile, " transform=\"translate(0 0) scale(1 1)\">\n" );

        return true;
    }

private:
    double m_exactWidthMm = 0.0;
    double m_exactHeightMm = 0.0;
};

} // namespace


bool RenderGerberToSvg( const wxString& aInputPath, const wxString& aOutputPath,
                        const GERBER_SVG_RENDER_OPTIONS& aOptions, wxString* aErrorMsg,
                        wxArrayString* aMessages )
{
    auto image = LoadGerberOrExcellon( aInputPath, aErrorMsg, aMessages );

    if( !image )
        return false;

    if( image->GetItemsCount() == 0 )
    {
        if( aErrorMsg )
            *aErrorMsg = wxS( "Gerber file contains no draw items" );

        return false;
    }

    BOX2I bbox;

    if( aOptions.HasViewportOverride() )
    {
        bbox = CalculateGerberViewportBoundingBox( aOptions.originXMm, aOptions.originYMm,
                                                   aOptions.windowWidthMm, aOptions.windowHeightMm );
    }
    else
    {
        bbox = CalculateGerberBoundingBox( image.get() );
    }

    if( bbox.GetWidth() == 0 || bbox.GetHeight() == 0 )
    {
        if( aErrorMsg )
            *aErrorMsg = wxS( "Gerber file has zero-size bounding box" );

        return false;
    }

    double pageWidthMm = static_cast<double>( bbox.GetWidth() ) / gerbIUScale.IU_PER_MM;
    double pageHeightMm = static_cast<double>( bbox.GetHeight() ) / gerbIUScale.IU_PER_MM;

    PAGE_INFO pageInfo( PAGE_SIZE_TYPE::User );
    pageInfo.SetWidthMM( pageWidthMm );
    pageInfo.SetHeightMM( pageHeightMm );

    GERBER_SVG_PLOTTER plotter;
    plotter.SetExactPageSizeMm( pageWidthMm, pageHeightMm );
    plotter.SetCreator( wxS( "KiCad" ) );
    plotter.SetColorMode( true );
    plotter.SetPageSettings( pageInfo );
    plotter.SetViewport( bbox.GetOrigin(), gerbIUScale.IU_PER_MILS / 10.0, 1.0, false );

    if( !plotter.OpenFile( aOutputPath ) )
    {
        if( aErrorMsg )
            *aErrorMsg = wxString::Format( wxS( "Failed to open SVG file: %s" ), aOutputPath );

        return false;
    }

    if( !plotter.StartPlot( wxEmptyString ) )
    {
        if( aErrorMsg )
            *aErrorMsg = wxS( "Failed to start SVG plotter" );

        return false;
    }

    if( aOptions.includeBackground && aOptions.backgroundColor.a > 0.0 )
    {
        plotter.SetColor( aOptions.backgroundColor );
        plotter.Rect( bbox.GetOrigin(), bbox.GetEnd(), FILL_T::FILLED_SHAPE, 0 );
    }

    RenderGerberImageToPlotter( image.get(), plotter, aOptions.foregroundColor, aOptions.backgroundColor );

    if( !plotter.EndPlot() )
    {
        if( aErrorMsg )
            *aErrorMsg = wxS( "Failed to finalize SVG plotter" );

        return false;
    }

    return true;
}


bool RenderGerberToSvg( const wxString& aInputPath, const wxString& aOutputPath,
                        const JOB_GERBER_EXPORT_SVG& aJob, wxString* aErrorMsg, wxArrayString* aMessages )
{
    GERBER_SVG_RENDER_OPTIONS options;
    options.includeBackground = aJob.m_includeBackground;

    if( !aJob.m_foregroundColor.IsEmpty() )
        options.foregroundColor = KIGFX::COLOR4D( aJob.m_foregroundColor );

    if( !aJob.m_backgroundColor.IsEmpty() )
        options.backgroundColor = KIGFX::COLOR4D( aJob.m_backgroundColor );

    double toMm = 1.0;

    switch( aJob.m_units )
    {
    case JOB_GERBER_EXPORT_SVG::UNITS::INCH: toMm = 25.4;   break;
    case JOB_GERBER_EXPORT_SVG::UNITS::MILS: toMm = 0.0254; break;
    case JOB_GERBER_EXPORT_SVG::UNITS::MM:   toMm = 1.0;    break;
    }

    options.originXMm = aJob.m_originX * toMm;
    options.originYMm = aJob.m_originY * toMm;
    options.windowWidthMm = aJob.m_windowWidth * toMm;
    options.windowHeightMm = aJob.m_windowHeight * toMm;

    return RenderGerberToSvg( aInputPath, aOutputPath, options, aErrorMsg, aMessages );
}
